image: python:3.9

pipelines:
  pull-requests:
    '**':
      - step:
          name: AI Code Review
          script:
            # Install dependencies
            - pip install git+https://github.com/yourusername/ai-code-reviewer.git
            # Run the review with environment variables
            - python -m ai_code_reviewer.cli --pr $BITBUCKET_PR_ID --platform bitbucket --post-comment
          services:
            - docker
          caches:
            - pip
          env:
            # Bitbucket credentials
            BITBUCKET_USERNAME: $BITBUCKET_USERNAME
            BITBUCKET_APP_PASSWORD: $BITBUCKET_APP_PASSWORD
            BITBUCKET_WORKSPACE: $BITBUCKET_WORKSPACE
            BITBUCKET_REPO_SLUG: $BITBUCKET_REPO_SLUG

            # Gemini AI configuration
            GEMINI_API_KEY: $GEMINI_API_KEY
            MAX_RETRIES: 3
            RETRY_DELAY: 2
            MODEL_NAME: models/gemini-2.5-flash-preview-04-17
            TEMPERATURE: 0.7
            MAX_TOKENS: 2048

definitions:
  caches:
    pip: ~/.cache/pip 